# config/routes/reset_password.yaml
app_forgot_password_request:
    path: /forgot-password
    methods: [GET, POST]

app_check_email:
    path: /check-email
    methods: [GET]

app_reset_password:
    path: /reset-password/{token}
    methods: [GET, POST]