controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_first_page:
    path: /
    controller: App\Controller\FirstPageController::index
# Remove this conflicting route definition
# entreprise_edit_profile:
#    path: /entreprise/profile/edit
#    controller: App\Controller\EntrepriseController::editProfile
# Si vous préférez définir la route ici plutôt que d'utiliser les attributs
app_entreprise_home:
    path: /entreprise
    controller: App\Controller\EntrepriseController::index



