controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_first_page:
    path: /
    controller: App\Controller\FirstPageController::index
# Remove this conflicting route definition
# entreprise_edit_profile:
#    path: /entreprise/profile/edit
#    controller: App\Controller\EntrepriseController::editProfile
# Si vous préférez définir la route ici plutôt que d'utiliser les attributs
app_entreprise_home:
    path: /entreprise
    controller: App\Controller\EntrepriseController::index
# Ajouter ces routes si elles ne sont pas déjà définies par les annotations
job_seeker_interview_behavioral_questions:
    path: /job-seeker/interview/behavioral-questions
    controller: App\Controller\JobSeeker\BehavioralQuestionController::index

job_seeker_interview_practice_question:
    path: /job-seeker/interview/behavioral-questions/{id}/practice
    controller: App\Controller\JobSeeker\BehavioralQuestionController::practiceQuestion

job_seeker_interview_practice_common_question:
    path: /job-seeker/interviews/practice/{id}
    controller: App\Controller\JobSeeker\CommonQuestionController::practiceQuestion
