controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes pour l'administration
admin_home:
    path: /admin
    controller: App\Controller\AdminController::index

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

admin_companies:
    path: /admin/companies
    controller: App\Controller\AdminController::companies

admin_job_seekers:
    path: /admin/job-seekers
    controller: App\Controller\AdminController::jobSeekers

admin_approve_company:
    path: /admin/company/{id}/approve
    controller: App\Controller\AdminController::approveCompany




